Chloeedeal/happo testing
manifoldco/ui pull request #97
Opened 2019-04-25 19:12 UTC by batgirl

Testing to see if TypeScript files are picked up by Happo.

2019-04-26 15:12 UTC, sslotsky commented on webpack.config.js
> +module.exports = {
The docs don't mention needing this. I was actually forced to use the TS plugin locally when I was messing with trying to mock fetch calls, and found that I didn't need it either. But I assume you must have found that you needed it, or else it wouldn't be here. What did you run into that required a custom webpack config?

2019-04-29 16:47 UTC, batgirl commented on webpack.config.js
> +module.exports = {
Oh yes, it wasn't working for me until I added this - the [happo typescript plugin](https://github.com/happo/happo-plugin-typescript) uses [ts-loader](https://github.com/TypeStrong/ts-loader) and was erroring out until I added it. This webpack config is from the ts-loader docs. Were you using the happo typescript plugin before?

2019-04-29 17:03 UTC, sslotsky commented on webpack.config.js
> +module.exports = {
I was, yes :confused:

2019-04-29 17:04 UTC, sslotsky commented on webpack.config.js
> +module.exports = {
I definitely need `ts-loader` but not the config file :man_shrugging:

2019-04-29 17:07 UTC, batgirl commented on webpack.config.js
> +module.exports = {
Oh maybe that's my case too then - it didn't work when I just installed ts-loader but it did once I added the config, but perhaps I added too much config, if that makes sense 😛

2019-04-29 17:07 UTC, batgirl commented on webpack.config.js
> +module.exports = {
I'll try again without the webpack file.

2019-04-29 19:15 UTC, sslotsky requested changes
Some tiny changes and then let's merge it :money_with_wings:

2019-04-29 19:15 UTC, sslotsky commented on src/components/manifold-select/manifold-select-happo.tsx
> +export const primary = (_render: void) => {
I had the `render` param in there from some async experiments, but we don't really need it. Let's change this to:

```js
export const primary = () => {
```

and then I think we can merge this one and close mine.

2019-04-29 19:15 UTC, sslotsky commented on src/components/manifold-select/manifold-select-happo.tsx
> +export const primary = (_render: void) => {
Also I suppose we can just name it `.ts` instead of `.tsx` because there's no JSX. Not a big deal.

2019-05-01 13:45 UTC, davidleger95 commented
Should this PR be closed? It seems similar to the one @sslotsky submitted.

2019-05-01 14:03 UTC, batgirl commented
Essentially a duplicate of https://github.com/manifoldco/ui/pull/93 for testing purposes. Closing.

2019-05-01 14:03 UTC, closed without merging